### ISSUE TITLE
StaggeredDividerItemDecoration bug

### ISSUE THREAD

**Issue by LLQQHH** [fondesa/recycler-view-divider#106]
6item is big than 5item,
for example: if i set space 10
5item offsetleft+offsetRight=10+5=15
6item offsetleft+offsetRight=5+5=10
so 6item is big than 5item
![微信截图_20200521165646](https://user-images.githubusercontent.com/19651932/82542237-3c6d3600-9b84-11ea-8c74-8f6f2a83c93d.png)
![TIM截图20200521165547](https://user-images.githubusercontent.com/19651932/82542256-42631700-9b84-11ea-8906-12fa4d835044.png)

**Comment by fondesa** [comment]
It's already opened this bug by another user: https://github.com/fondesa/recycler-view-divider/issues/79

**Comment by fondesa** [comment]
We can discuss about it in the already opened issue: https://github.com/fondesa/recycler-view-divider/issues/79

**Comment by fondesa** [comment]
Fixed in the version **3.3.0** (only using the new API, not the legacy one).
