### ISSUE TITLE
GridLayoutManager item height not equal

### ISSUE THREAD

**Issue by kjsolo** [fondesa/recycler-view-divider#118]
### Description

- Side divider size is 16dp
- Middle divider size is 10dp

Middle item height different from others

<img width="746" alt="WX20200609-113413@2x" src="https://user-images.githubusercontent.com/590893/84103362-6314e300-aa45-11ea-83e9-49c05cef3c70.png">

-----------

**RecyclerViewDivider version**:
3.3.0

**Comment by fondesa** [comment]
This library doesn't do anything on item's height but the offset could change only the item's width. Maybe the middle item has a different width from the others and the height you are using is based on the width?

**Comment by kjsolo** [comment]
This is my solution

```kotlin
object : DividerOffsetProvider {
    override fun getOffsetFromSize(grid: Grid, divider: Divider, dividerSide: Side, size: Int): Int {
        if (divider.isTopDivider || divider.isBottomDivider || divider.isStartDivider || divider.isEndDivider) return size
        val gridOrientation = grid.orientation
        if (gridOrientation.isVertical && dividerSide == Side.TOP || gridOrientation.isHorizontal && dividerSide == Side.START) return 0
        if (gridOrientation.isVertical && dividerSide == Side.BOTTOM || gridOrientation.isHorizontal && dividerSide == Side.END) return size

        val sideDividerSize = 16.dp

        val cellsCount = grid.lines[divider.originY].cellsCount
        if (cellsCount >= 3) {
            val fixedSize = (cellsCount - 2) * sideDividerSize
            val allocatableSize = size * (cellsCount - 1) - fixedSize
            val averageSize = allocatableSize / cellsCount.toFloat()

            if (divider.originX == 1 && dividerSide == Side.END
                || divider.originX == cellsCount - 1 && dividerSide == Side.START) {
                return averageSize.toInt()
            } else {
                val middleCellDividerSize = (sideDividerSize + averageSize) / 2
                return middleCellDividerSize.toInt()
            }
        } else {
            return size
        }
    }
}
```

<img width="505" alt="WX20200609-162644@2x" src="https://user-images.githubusercontent.com/590893/84124593-05e15780-aa6e-11ea-889b-f35dbf7f7ae9.png">

**Comment by fondesa** [comment]
Perfect, you are probably the first one using the new `DividerOffsetProvider` API 🥇

**Comment by kjsolo** [comment]
You can consider passing `sideDividerSize` as a argument to the `OffsetProvider`, Make the library easier :)
