### ISSUE TITLE
Grag  Item,the space will bigger and bigger

### ISSUE THREAD

**Issue by caiyoufei** [fondesa/recycler-view-divider#132]
![GIF](https://user-images.githubusercontent.com/11989916/99666520-afa52580-2a9d-11eb-96bc-00c64267ce21.gif)

**Comment by caiyoufei** [comment]
when i use GridLayoutManager,count is 3
the second item,height more than first and third

**Comment by fondesa** [comment]
Hi, thanks for submitting this issue.
Can you provide a sample of the bug so I can investigate it further?

**Comment by caiyoufei** [comment]
Use normal RecyclerView:
Adapter：MultiType
https://github.com/LidongWen/MultiTypeAdapter/blob/master/app/src/main/java/com/wenld/app_multitypeadapter/itemTouch/ItemTouchMoveListener.java
Drag:
https://github.com/LidongWen/MultiTypeAdapter/blob/master/app/src/main/java/com/wenld/app_multitypeadapter/itemTouch/ItemTouchMoveListener.java
https://github.com/LidongWen/MultiTypeAdapter/blob/master/app/src/main/java/com/wenld/app_multitypeadapter/itemTouch/MyItemTouchHelperCallback.java

**Comment by caiyoufei** [comment]
You can try to add drag effect
