### ISSUE TITLE
How to use the SizeProvider

### ISSUE THREAD

**Issue by git-maven** [fondesa/recycler-view-divider#218]
i want to give the gridView an different spacing like Flutter that use mainAxisSpacing and crossAxisSpacing
i know i must use the SizeProvider, but i want to use the position to accumulate it, but it donnt provided

**Comment by fondesa** [comment]
To do that, you have to use the properties of the instance of `Divider` passed to the `SizeProvider` method.

For example, in a vertical grid, you have to use `Divider.originY` for the dividers drawn horizontally and `Divider.originX` for the dividers drawn vertically.

Check the [documentation](https://github.com/fondesa/recycler-view-divider/blob/master/recycler-view-divider/src/main/kotlin/com/fondesa/recyclerviewdivider/Divider.kt) of `Divider` which makes a lot of examples which explain this behavior better.

If you have further doubts related to `SizeProvider`, feel free to reopen this issue.
