### ISSUE TITLE
Add .colorRes, .drawableRes methods 

### ISSUE THREAD

**Issue by AlexandreGorobets** [fondesa/recycler-view-divider#97]
Hello!
Builder for RecyclerViewDivider have context, so you can add method that can make code more clean

` RecyclerViewDivider.with(context).color(ContextCompat.getColor(context, R.color.divider)).build()`

will be:

` RecyclerViewDivider.with(context).colorRes(R.color.divider).build()`

**Comment by fondesa** [comment]
Hi, nice idea. I was releasing the version **3.2.0** in this exact moment. I stopped the release so I can add this API.

Be ready because from **3.2.0** on, the `RecyclerViewDivider` API will be deprecated in favour of the new `DividerBuilder` API.

**Comment by fondesa** [comment]
@AlexandreGorobets Here we go: https://github.com/fondesa/recycler-view-divider/pull/98

**Comment by fondesa** [comment]
Just released the version [3.2.0](https://github.com/fondesa/recycler-view-divider/releases/tag/3.2.0) which contains `colorRes` and `drawableRes`.

**e.g.** (kotlin)

```kotlin
context.dividerBuilder().colorRes(R.color.divider).build()
```
